default-task = 'build'
version = 0.1

extensions = ['chomp@0.1:jspm', 'chomp@0.1:npm']

[template-options.npm]
auto-install = true

[[task]]
name = 'build'
deps = ['index.html', 'npm:install']
engine = 'node'
invalidation = 'always'
run = '''
    import { Generator } from '@jspm/generator';
    import { readFile, writeFile } from 'fs/promises';
    import { pathToFileURL } from 'url';
    import mkdirp from 'mkdirp';
    import { dirname } from 'path';

    const generator = new Generator({
      mapUrl: pathToFileURL(process.env.TARGET),
      env: ["browser", "production"]
    });

    const htmlSource = await readFile(process.env.DEP, 'utf-8');

    mkdirp.sync(dirname(process.env.TARGET));
    await writeFile(process.env.TARGET, await generator.htmlInject(htmlSource, {
      // custom task required to set this up for now!
      htmlUrl: pathToFileURL('process.env.TARGET'),
      preload: true,
      integrity: true, // erring ATM
      whitespace: true,
      esModuleShims: true,
      comment: true,
      trace: true
    }));
'''
target = 'tree.html'